#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 7.5
#  in conjunction with Tcl version 8.6
#    Aug 06, 2022 12:01:27 AM +03  platform: Windows NT
#    Aug 06, 2022 12:36:58 AM +03  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import calc


def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW' , root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = calc.Toplevel1(_top1)
    root.mainloop()

snum=""
def getnum(p1,p2):
    global snum
    snum += p2.cget('text')
    _w1.scr.configure(text=snum)    
def getres(e):
    global snum
    global t
    c=0
    b=1
    t=False
    for i in snum:
        if i=='^':
            t=True
            if c==1:
                a=int(snum[c-1])
                for x in range(int(snum[c+1])):
                    b=b*a
            elif c==2:
                a=int(snum[c-2]+snum[c-1])
                for x in range(int(snum[c+1])):
                    b=b*a
            else:
                _w1.scr.configure(text=
                """Please Calculate The
Exponential Function
First""")
                return
            
        c=c+1
    

        
    if t==True:
        _w1.scr.configure(text=b)
        snum=str(b)
    else:
        _w1.scr.configure(text=eval(snum))
        snum=str(eval(snum))
        
def delete(e):
    global snum
    snum=snum[:-1]
    _w1.scr.configure(text=snum)
    _w1.LblDel.configure(foreground="#ffffff")

def l(e):
    _w1.LblDel.configure(foreground="#808c8a")


def clear(e):
    global snum
    snum=""
    _w1.scr.configure(text=snum)


       
if __name__ == '__main__':
    calc.start_up()





